
GET https://localhost:7271/api/moviesapi/allMovies

###
POST https://localhost:7271/api/moviesapi/create
Content-Type: application/json
{
  "name": "Mama Ryzvielt",
  "description": "Nazi is bad ones like realy bad"
}

###
GET https://localhost:7271/api/moviesapi/moviesById/3
